### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by torchsmith** [Jacksonmills/oki#1]
I had a tab open all day and it didn't disconnect me from the UI, but it did disconnect me from the server. Showed 0 people online and couldn't send messages. Not sure what the disconnect would be caused by, if you were working on stuff, or a timeout, or what.

**Comment by Jacksonmills** [comment]
Yeah I need to look to see if socket.io has a fix for this or watch for this case and fire the reconnect event maybe

**Comment by torchsmith** [comment]
Closing as this project seems to have been abandoned.
